In [1]:
import pandas as pd

df = pd.read_csv("../data/Telco_Customer_Churn.csv")

In [3]:
# Finding fundamental facts
print(f"Size of dataset is {df.shape}")

Size of dataset is (7043, 21)

In [4]:
print(f"Datatypes present in data :- \n{df.dtypes}")

Datatypes present in data :-
customerID              str
gender                  str
SeniorCitizen         int64
Partner                 str
Dependents              str
tenure                int64
PhoneService            str
MultipleLines           str
InternetService         str
OnlineSecurity          str
OnlineBackup            str
DeviceProtection        str
TechSupport             str
StreamingTV             str
StreamingMovies         str
Contract                str
PaperlessBilling        str
PaymentMethod           str
MonthlyCharges      float64
TotalCharges            str
Churn                   str
dtype: object

In [5]:
print(f"Total Null values in the dataset :- {df.isnull().sum()}")

Total Null values in the dataset :- customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [6]:
print(f"Class imbalance check :- {df['Churn'].value_counts(normalize=True)}")

Class imbalance check :- Churn
No     0.73463
Yes    0.26537
Name: proportion, dtype: float64

### Observe that ~73% are non-churners and ~27% are churners. Indicating class imbalance.

In [7]:
# TotalCharges is being read as a string. Convert it to numeric

df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
df['TotalCharges'].isnull().sum()

np.int64(11)

In [10]:
# Univariate Analysis for numeric columns
df[['tenure', 'MonthlyCharges', 'TotalCharges']].describe()

            tenure  MonthlyCharges  TotalCharges
count  7043.000000     7043.000000   7032.000000
mean     32.371149       64.761692   2283.300441
std      24.559481       30.090047   2266.771362
min       0.000000       18.250000     18.800000
25%       9.000000       35.500000    401.450000
50%      29.000000       70.350000   1397.475000
75%      55.000000       89.850000   3794.737500
max      72.000000      118.750000   8684.800000

In [11]:
# Univariate Analysis for categorical columns
cat_cols = df.select_dtypes(include='object').columns
for col in cat_cols:
    print(df[col].value_counts(), "\n")

customerID
7590-VHVEG    1
5575-GNVDE    1
3668-QPYBK    1
7795-CFOCW    1
9237-HQITU    1
             ..
6840-RESVB    1
2234-XADUH    1
4801-JZAZL    1
8361-LTMKD    1
3186-AJIEK    1
Name: count, Length: 7043, dtype: int64

gender
Male      3555
Female    3488
Name: count, dtype: int64

Partner
No     3641
Yes    3402
Name: count, dtype: int64

Dependents
No     4933
Yes    2110
Name: count, dtype: int64

PhoneService
Yes    6361
No      682
Name: count, dtype: int64

MultipleLines
No                  3390
Yes                 2971
No phone service     682
Name: count, dtype: int64

InternetService
Fiber optic    3096
DSL            2421
No             1526
Name: count, dtype: int64

OnlineSecurity
No                     3498
Yes                    2019
No internet service    1526
Name: count, dtype: int64

OnlineBackup
No                     3088
Yes                    2429
No internet service    1526
Name: count, dtype: int64

DeviceProtection
No                     3095
Yes                    2422
No internet service    1526
Name: count, dtype: int64

TechSupport
No                     3473
Yes                    2044
No internet service    1526
Name: count, dtype: int64

StreamingTV
No                     2810
Yes                    2707
No internet service    1526
Name: count, dtype: int64

StreamingMovies
No                     2785
Yes                    2732
No internet service    1526
Name: count, dtype: int64

Contract
Month-to-month    3875
Two year          1695
One year          1473
Name: count, dtype: int64

PaperlessBilling
Yes    4171
No     2872
Name: count, dtype: int64

PaymentMethod
Electronic check             2365
Mailed check                 1612
Bank transfer (automatic)    1544
Credit card (automatic)      1522
Name: count, dtype: int64

Churn
No     5174
Yes    1869
Name: count, dtype: int64

/var/folders/ch/6_wcgph164jdzq9spqkmbhzw0000gn/T/ipykernel_52552/2507797819.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = df.select_dtypes(include='object').columns

## Churn Rate by Categorical Variables

In [ ]:
cat_features = ['gender', 'SeniorCitizen', 'Partner', 'Dependents',
                'PhoneService', 'MultipleLines', 'InternetService',
                'OnlineSecurity', 'Contract', 'PaymentMethod', 'PaperlessBilling']

for col in cat_features:
    churn_rate = df.groupby(col)['Churn'].apply(lambda x: (x == 'Yes').mean())
    print(churn_rate.sort_values(ascending=False), "\n")

gender
Female    0.269209
Male      0.261603
Name: Churn, dtype: float64

SeniorCitizen
1    0.416813
0    0.236062
Name: Churn, dtype: float64

Partner
No     0.329580
Yes    0.196649
Name: Churn, dtype: float64

Dependents
No     0.312791
Yes    0.154502
Name: Churn, dtype: float64

PhoneService
Yes    0.267096
No     0.249267
Name: Churn, dtype: float64

MultipleLines
Yes                 0.286099
No                  0.250442
No phone service    0.249267
Name: Churn, dtype: float64

InternetService
Fiber optic    0.418928
DSL            0.189591
No             0.074050
Name: Churn, dtype: float64

OnlineSecurity
No                     0.417667
Yes                    0.146112
No internet service    0.074050
Name: Churn, dtype: float64

Contract
Month-to-month    0.427097
One year          0.112695
Two year          0.028319
Name: Churn, dtype: float64

PaymentMethod
Electronic check             0.452854
Mailed check                 0.191067
Bank transfer (automatic)    0.167098
Credit card (automatic)      0.152431
Name: Churn, dtype: float64

PaperlessBilling
Yes    0.335651
No     0.163301
Name: Churn, dtype: float64

In [17]:
# Encode churn and check correlations
df['Churn_binary'] = (df['Churn'] == 'Yes').astype(int)
df[['tenure', 'MonthlyCharges', 'TotalCharges', 'Churn_binary']].corr()

                  tenure  MonthlyCharges  TotalCharges  Churn_binary
tenure          1.000000        0.247900      0.825880     -0.352229
MonthlyCharges  0.247900        1.000000      0.651065      0.193356
TotalCharges    0.825880        0.651065      1.000000     -0.199484
Churn_binary   -0.352229        0.193356     -0.199484      1.000000

## Churn Rate by Numerical variables

In [ ]:
df['Churn_binary'] = (df['Churn'] == 'Yes').astype(int)

df.groupby('Churn')[['tenure', 'MonthlyCharges', 'TotalCharges']].mean()

          tenure  MonthlyCharges  TotalCharges
Churn
No     37.569965       61.265124   2555.344141
Yes    17.979133       74.441332   1531.796094

## Churning based on tenure segment

In [ ]:
# Creating tenure groups
df['tenure_group'] = pd.cut(df['tenure'], bins=[0, 12, 24, 48, 72],
                             labels=['0-1yr', '1-2yr', '2-4yr', '4-6yr'])

In [15]:
df.groupby('tenure_group')['Churn_binary'].mean()

tenure_group
0-1yr    0.476782
1-2yr    0.287109
2-4yr    0.203890
4-6yr    0.095132
Name: Churn_binary, dtype: float64

## Revenue at risk

In [16]:
churned = df[df['Churn'] == 'Yes']
print(f"Monthly revenue at risk: ${churned['MonthlyCharges'].sum():,.0f}")
print(f"Avg monthly charge (churned): ${churned['MonthlyCharges'].mean():.2f}")
print(f"Avg monthly charge (retained): ${df[df['Churn']=='No']['MonthlyCharges'].mean():.2f}")

Monthly revenue at risk: $139,131
Avg monthly charge (churned): $74.44
Avg monthly charge (retained): $61.27

## Key Insights

- There are ~73% non-churners and ~27% churners, indicating some class imbalance.
- Month-to-month contracts churn at ~40% vs ~3% for two-year contracts
- Fiber optic internet users churn more than DSL users
- Customers without OnlineSecurity churn far more
- Churned customers have much lower tenure (avg ~18 months vs ~38 for retained) (Also indicated by negative correlation between Tenure and Churn feature)
- Churned customers pay higher monthly charges on average
- TotalCharges is lower for churned (short tenure × high monthly)